---
title: "Template Title"
author: "Niklas Hausmann"
date: "Today"
output: pdf_document
---

# Libraries 
```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}
```

# Data

```{r}
QGShell <- read_csv(file=here("data","QG1-7246-1-A30Centre_analyzed_data.csv"), col_names = c("x", "y", "z", "mg_ca", "std", "relstd")) %>%
  mutate(sampleID = "QG1-7246-1") %>%
  filter(relstd<0.1,
         x>1.3) %>% 
  mutate(x=round(x,2)) %>% 
  group_by(y) %>% 
  mutate(mg_ca=mean(mg_ca),
         std=mean(std),
         n=n()) %>% 
  ungroup() %>% 
  filter(n>1) %>% 
  select(sampleID,everything(),-n) %>% 
  arrange(y) %>% 
  mutate(dist=row_number()*0.03)




QGShell %>% 
  ggplot()+
  aes(y,mg_ca)+
  geom_line()


```



```{r}

write_csv(bind_rows(MgCa,QGShell),file=here("data","MgCa.csv"))



```

