---
title: "Interspecies comparisons of Mg/Ca ratios in limpet shells"
author:
  - name: Niklas Hausmann
    affiliations:
      - name: Leibniz Zentrum für Archäologie
        address: Ludwig-Lindenschmit-Forum 1
        city: Mainz
        country: Germany
        postal-code: 55116
    orcid: 0000–0002–4381–8334
    email: niklas@palaeo.eu
    attributes:
      corresponding: true
  - name: Donna Surge
    affiliations:
      - name: University of North Carolina
        address: 104 South Road, 225 Geology Building
        city: Chapel Hill, NC
        country: US
        postal-code: 27599-3315
  - name: Francisco Zangrando
    affiliations:
      - name: CONICET (Consejo Nacional de Investigaciones Científicas y Técnicas)
        address: Avenida Maipú 305
        city: Ushuaia
        country: Argentina
        postal-code: V9410BJA
  - name: Angelica Tivoli
    affiliations:
      - name: CONICET (Consejo Nacional de Investigaciones Científicas y Técnicas)
        address: Avenida Maipú 305
        city: Ushuaia
        country: Argentina
        postal-code: V9410BJA
  - name: Ivan Briz-Godino
    affiliations:
      - name: 
        address: 
        city: 
        country: Spain
        postal-code: 
abstract: |
  This document is a template demonstrating the Aps format.
keywords: 
  - keyword1
  - keyword2
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Palaeo^3^
      formatting: preprint
      model: 3p
      cite-style: authoryear
output:
  units: cm
---

# Introduction {#Introduction}

```{r Libray and datasets}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE

knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)
# Packages
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,ggpubr,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())

# Scripts
source("DTW_Script.R")

  
# Files  


D18O <- read_csv(here("data","D18O.csv"))
MgCa <- read_csv(here("data","MgCa.csv"))


# # Check overlaps
# # Find common sample IDs
# intersect(MgCa$sampleID, D18O$sampleID)
# 
# # Find sample IDs only in MgCa
# setdiff(MgCa$sampleID, D18O$sampleID)
# 
# # Find sample IDs only in D18O
# setdiff(D18O$sampleID, MgCa$sampleID)

```

# Methods {#Methods}

```{r DTW Analysis}

Samples <- unique(MgCa$sampleID)

# Initialize an empty list to store the results of shell_dtw for each sample
dtw_results <- list()

Corr_data <- tibble()

sample <- Samples[6]

for (sample in Samples) {
  temp_D18O <- D18O %>% 
    filter(sampleID == sample) %>% 
    select(d18O) %>% 
    rename(d18o = d18O) %>% 
    mutate(sample_seq = row_number()) 

  temp_MgCa <- MgCa %>% 
    filter(sampleID == sample) %>% 
    filter(!(sampleID=="ND-1016-4"&dist<0.3)) %>% 
    select(mg_ca) %>% 
    mutate(sample_seq = row_number())

  # Apply shell_dtw to the temp dataframes and store the result in the list
  dtw_results[[sample]] <- shell_dtw_data(temp_D18O, temp_MgCa)
  
   # Add the sampleID column to temp_data
  temp_data <- dtw_results[[sample]]$data %>% 
    mutate(sampleID = sample)
  
  
  # Append temp_data to Corr_data
  Corr_data <- bind_rows(Corr_data, temp_data)
}


```

# Results {#Results}

```{r Correlation Graphs }
#| fig-cap: Correlation graphs for all specimens
#| fig-height: 20
#| fig-width: 10


P_all <- Corr_data %>% 
  pivot_wider(values_from = "value",names_from = "proxy") %>% 
  mutate(region = substr(sampleID, 1, 1)) %>% 
  ggplot()+
  aes(d18o,mg_ca,col=sampleID)+
  geom_point(show.legend = FALSE)+
  labs(x=expression("‰ δ" ^ "18" * "O [VPDB]"),y="Mg/Ca intensity ratio")+
  stat_smooth(aes(fill = sampleID,col=sampleID), method = "lm", formula = y~x,show.legend = FALSE) +
  # stat_regline_equation(label.x = 2, #label.y = 32
  #   aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
  #   formula = y~x
  # ) +
  scale_colour_manual(values = c( "#33a02c","#2ecc71", "#ffc100", "#f39c12", "#007f7f", "#1f78b4", "#99d8c9", "#542788","black", "#d73027", "#EC7063")) +
scale_fill_manual(values = c( "#33a02c","#2ecc71", "#ffc100", "#f39c12", "#007f7f", "#1f78b4", "#99d8c9", "#542788","black", "#d73027", "#EC7063"))#+
  # facet_wrap(~region,ncol=2,scales = "free")


# Expanded colour palette with 6 additional colours
# Updated colour palette with 4 new replacements for the last colours
# Refined colour palette with 3 additional colours
# c("#007f7f", "#d73027", "#ffc100", "black", "#1a9850", "#542788", "#3288bd", "#99d8c9")


P_individual <- P_all+ylim(0,0.8)+
  facet_wrap(~sampleID,ncol=3)+#ylim(0.15,NA)+
  ggpubr::stat_regline_equation(label.x = 0.5, label.y = 0.65,
    aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),show.legend = FALSE,
    formula = y~x
  )+
  theme(
    strip.background = element_rect(fill = "white", colour = NA),
    strip.text = element_text(colour = "black"),
    panel.border = element_rect(colour="black")
  )


P_all/P_individual+plot_layout(heights = c(0.5,0.5))




```

| Species            | Locality       | Specimen | Correlation R^2^ | Study                                                          |
|-------------------|---------------|---------------|---------------|---------------|
| *Patella depressa* | Northern Spain | LAN541   | 0.87             | [**10.3390/app11072959**](https://doi.org/10.3390/app11072959) |
|                    |                | LAN545   | 0.86             |                                                                |
|                    |                | LAN554   | 0.78             |                                                                |
|                    |                | LAN559   | 0.82             |                                                                |
| Patella caerulea   | Croatia        | ISTPC1   | 0.9              | 10.1038/s41598-019-39959-9                                     |
|                    |                | ISTPC2   | 0.84             |                                                                |
|                    | Crete          | AF1911A  | 0.91[^1]         |                                                                |
|                    |                | AF3003A  | 0.92[^2]         |                                                                |
|                    | Israel         | AKKPC2   | 0.96             |                                                                |
|                    |                | AKKPC3   | 0.89             |                                                                |
|                    |                | FRMPC1   | 0.84             |                                                                |
|                    |                | FRMPC2   | 0.96             |                                                                |
|                    | Libya          | MO31A    | 0.83             |                                                                |
|                    |                | MP64A    | 0.33             |                                                                |
|                    |                | MP67A    | 0.96             |                                                                |
|                    |                | MP68A    | 0.81             |                                                                |
|                    | Malta          | MA10     | 0.82             |                                                                |
|                    | Tunisia        | TUNPC1   | 0.81             |                                                                |
|                    |                | TUNPC2   | 0.78             |                                                                |
|                    | Turkey         | ANTPC1   | 0.95             |                                                                |
|                    |                | ANTPC2   | 0.93             |                                                                |
|                    |                | KIZPC1   | 0.94             |                                                                |
|                    |                | KIZPC2   | 0.86             |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |
|                    |                |          |                  |                                                                |

: Overview of comparative correlations {#tab:correlations}

[^1]: SST only, no other geochemical data available

[^2]: SST only, no geochemical data available
